# Generated by Django 5.1.2 on 2025-04-04 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationTokensModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=204)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgrameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffDepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=240)),
                ('last_name', models.CharField(max_length=240)),
                ('email', models.EmailField(db_index=True, max_length=240, unique=True)),
                ('username', models.CharField(max_length=240, unique=True)),
                ('profile_img', models.ImageField(blank=True, default='', null=True, upload_to='profile_images/')),
                ('hasFullAccess', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staffdepartmentmodel')),
            ],
            options={
                'verbose_name': 'Staff User',
                'verbose_name_plural': 'Staff Users',
            },
        ),
        migrations.CreateModel(
            name='StudentstsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('surname', models.CharField(max_length=255)),
                ('othername', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('indexNumber', models.CharField(max_length=20, unique=True)),
                ('profile_img', models.ImageField(blank=True, default='', null=True, upload_to='students_images/')),
                ('groups', models.ManyToManyField(related_name='students_groups', to='auth.group')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programemodel')),
                ('user_permissions', models.ManyToManyField(related_name='students_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Custom Participant User',
                'verbose_name_plural': 'Custom Participant Users',
            },
        ),
        migrations.CreateModel(
            name='StudentsTokenStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.CharField(max_length=240)),
                ('refToken', models.CharField(max_length=240)),
                ('dateCreated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentstsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TokenStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.CharField(max_length=240)),
                ('refToken', models.CharField(max_length=240)),
                ('dateCreated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
