# Generated by Django 5.1.2 on 2025-04-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffusermodel',
            old_name='department',
            new_name='staffDepartment',
        ),
        migrations.RemoveField(
            model_name='staffusermodel',
            name='username',
        ),
    ]
