# Generated by Django 5.1.2 on 2025-04-04 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_department_staffusermodel_staffdepartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffusermodel',
            name='staffDepartment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.staffdepartmentmodel'),
        ),
    ]
