# Generated by Django 5.1.2 on 2025-04-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_staffusermodel_staffdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffusermodel',
            name='staffDepartment',
            field=models.CharField(default='', max_length=240),
        ),
    ]
