# Generated by Django 5.1.2 on 2025-06-04 23:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_staffusermodel_staffdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_id', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('current_semester', models.IntegerField(default=1)),
                ('academic_year', models.CharField(default='2023/2024', max_length=20)),
                ('academic_year_start', models.DateField(default='2023-08-01')),
                ('academic_year_end', models.DateField(default='2024-07-31')),
                ('academic_year_levels', models.CharField(default='100,200,300,400', max_length=255)),
                ('academic_year_levels_tution', models.CharField(default='1000,1200,1500,1800', max_length=255)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='studentstsmodel',
            options={'verbose_name': 'Student User', 'verbose_name_plural': 'Student Users'},
        ),
        migrations.AddField(
            model_name='staffusermodel',
            name='staffDepartment',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='studentstsmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='courseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('crh', models.CharField(max_length=15)),
                ('semester', models.CharField(max_length=5)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programemodel')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.levelmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegisterCourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('stud_uuid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('courses', models.CharField(max_length=255, unique=True)),
                ('dateRegistered', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('semester', models.CharField(max_length=5)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.levelmodel')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programemodel')),
            ],
        ),
    ]
