# Generated by Django 5.1.2 on 2025-06-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_levelmodel_settingsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
