# Generated by Django 5.1.2 on 2025-04-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staffusermodel_staffdepartment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentstsmodel',
            options={'verbose_name': 'Student User', 'verbose_name_plural': 'Student Users'},
        ),
        migrations.AddField(
            model_name='studentstsmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
