# Generated by Django 5.1.2 on 2025-06-11 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_settingsmodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstsmodel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.levelmodel'),
        ),
    ]
