# Generated by Django 5.1.2 on 2025-06-11 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_studentstsmodel_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffDepartmentModel',
            new_name='DepartmentModel',
        ),
    ]
