# Generated by Django 5.1.2 on 2025-04-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_coursemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='crh',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
