# Generated by Django 5.1.2 on 2025-06-11 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tutionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='isGeneral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentstsmodel',
            name='minor_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students_minor', to='core.programemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentstsmodel',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_major', to='core.programemodel'),
        ),
    ]
