# Generated by Django 5.1.2 on 2025-06-11 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_coursemodel_isgeneral_studentstsmodel_minor_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.programemodel'),
        ),
    ]
