# Generated by Django 5.1.2 on 2025-06-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_coursemodel_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='isJHS',
            field=models.BooleanField(default=True),
        ),
    ]
