# Generated by Django 5.1.2 on 2025-05-22 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_coursemodel_crh'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_id', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('current_semester', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CourseUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('courseTitle', models.CharField(max_length=255, unique=True)),
                ('courseCode', models.CharField(max_length=15, unique=True)),
                ('crh', models.CharField(max_length=15)),
                ('semester', models.CharField(max_length=5)),
                ('dateUploaded', models.DateTimeField(auto_now_add=True)),
                ('uploadedBy', models.CharField(max_length=255, unique=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.levelmodel')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programemodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegisterCourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('stud_uuid', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('courses', models.CharField(max_length=255, unique=True)),
                ('dateRegistered', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('semester', models.CharField(max_length=5)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.levelmodel')),
            ],
        ),
    ]
