# Generated by Django 5.1.2 on 2025-06-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_coursemodel_isjhs'),
    ]

    operations = [
        migrations.AddField(
            model_name='programemodel',
            name='minor',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
