# Generated by Django 5.1.2 on 2025-05-26 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_settingsmodel_courseuploadmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistercoursemodel',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.programemodel'),
        ),
        migrations.DeleteModel(
            name='CourseUploadModel',
        ),
    ]
