# Generated by Django 5.1.2 on 2025-05-26 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_studentregistercoursemodel_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistercoursemodel',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programemodel'),
        ),
    ]
