# Generated by Django 5.1.2 on 2025-06-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_programemodel_minor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programemodel',
            name='minor',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
