# Generated by Django 5.1.2 on 2025-06-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_programemodel_minor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentstsmodel',
            name='minor_program',
        ),
        migrations.AlterField(
            model_name='programemodel',
            name='minor',
            field=models.CharField(max_length=255),
        ),
    ]
