# Generated by Django 5.1.2 on 2025-06-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_studentstsmodel_minor_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programemodel',
            name='minor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
