# Generated by Django 5.1.2 on 2025-06-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_programslevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstsmodel',
            name='isProgramJHS',
            field=models.BooleanField(default=True),
        ),
    ]
