# Generated by Django 5.1.2 on 2025-06-14 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_studentstsmodel_isprogramjhs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffusermodel',
            name='staffDepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_department', to='core.departmentmodel'),
        ),
    ]
