# Generated by Django 5.1.2 on 2025-06-14 04:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_staffusermodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffusermodel',
            name='uid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True, unique=True),
        ),
    ]
