# Generated by Django 5.1.2 on 2025-06-15 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_staffusermodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffusermodel',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tutionmodel',
            name='academicYear',
            field=models.CharField(max_length=10),
        ),
    ]
