# Generated by Django 5.1.2 on 2025-08-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_staffusermodel_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifiedStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexNumber', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
