# Generated by Django 5.1.2 on 2025-08-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_qualifiedstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('indexNumber', models.CharField(max_length=20, unique=True)),
                ('program', models.CharField(max_length=100)),
                ('gpa', models.CharField(max_length=20)),
                ('gpaClass', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='qualifiedstudents',
            name='indexNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
