# Generated by Django 5.1.2 on 2025-08-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_graduationregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('indexNumber', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
