# Generated by Django 5.1.2 on 2025-08-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_graduants'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xlsFile', models.FileField(blank=True, null=True, upload_to='xlsFiles/')),
            ],
        ),
    ]
