# Generated by Django 5.1.2 on 2025-08-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_graduationlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationlist',
            name='xlsName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
